# -*- encoding=utf-8 -*-
__author__ = 'golding'

class Version:
    def __init__(self,):
        self.versionList = []

    def addVersion(self, strNo, strContent):
        self.versionList.append(dict(version = strNo, content = strContent))

    def getCurrentVersion(self):
        if len(self.versionList)>0:
            return self.versionList[-1].get('version')
        else:
            return '0.0.0'

    def getAllVersionUpdateJson(self):
        return self.versionList

siteVersion = Version()
siteVersion.addVersion('0.2.0', '增加了操作记录')
siteVersion.addVersion('0.2.1', '增加了版本管理，配置管理，修复了操作记录的()问题')
siteVersion.addVersion('0.2.2', '增加了本地发送邮件通知的功能')
siteVersion.addVersion('0.2.3', '支持了报表接口，增加了虚线图元及通用图元')
siteVersion.addVersion('0.2.4', '')
siteVersion.addVersion('0.2.2.20171006', '增加了本地发送邮件通知的功能')
siteVersion.addVersion('0.2.3.20171110', '支持了报表接口，增加了虚线图元及通用图元')
siteVersion.addVersion('0.2.4_20180411', '')
siteVersion.addVersion('0.2.4_20180414', '')
siteVersion.addVersion('0.2.6_20180612', '')
siteVersion.addVersion('0.2.7_20180630', '')
siteVersion.addVersion('0.2.8_20180723', '')
siteVersion.addVersion('0.2.9_20180806', '')
siteVersion.addVersion('0.2.10_20180811', '')
siteVersion.addVersion('0.2.11_20180902', '')
siteVersion.addVersion('0.2.12_20180917','')

siteVersion.addVersion('0.2.13_20180925','')

siteVersion.addVersion('0.2.14_20180926','修改了报表bug，增加了注册码支持')


siteVersion.addVersion('0.2.15_20180927','')
siteVersion.addVersion('0.2.16_20180928','故障诊断后台接口完善')

siteVersion.addVersion('0.2.17_20181026','增加报表API，Excel报表增加画图功能')


siteVersion.addVersion('0.2.17_20181010','点信息接口容错处理')
siteVersion.addVersion('0.2.18_20181011','故障诊断接口请求速度升级')
siteVersion.addVersion('0.2.19_20181012','修复故障诊断接口返回的字段名groupName')
siteVersion.addVersion('0.2.20_20181012','修复历史数据接口')
siteVersion.addVersion('0.2.21_20181018','增加factory的报表下载接口')
siteVersion.addVersion('0.2.22_20181023','增加domhost重启的当前目录处理')
siteVersion.addVersion('0.2.23_20181101','修复诊断信息接口')
siteVersion.addVersion('0.2.24_20181101','修复历史数据表创建')
siteVersion.addVersion('0.2.25_20181106','修复word报表里字体问题')
siteVersion.addVersion('0.2.25_20181109','增加后台报警接口health')
siteVersion.addVersion('0.2.26_20181109','增加单元测试,修复Excel报表格式问题')
siteVersion.addVersion('0.2.27_20181119','增加modbus,logo,等静态文件初始化支持')
siteVersion.addVersion('0.3.1_20181127','增加对不同db文件支持，数据库密码和数据库名的切换支持')
siteVersion.addVersion('0.3.2_20181127','修改能源费用报表返回数据')
siteVersion.addVersion('0.3.3_20181128','修复全局配置接口参数为空时报错的bug')
siteVersion.addVersion('0.3.4_20181129','修复thirdpary支持的bug')
siteVersion.addVersion('0.3.5_20181203','能源费用报表返回增加支路数据')
siteVersion.addVersion('0.3.6_20181203','修复能源费用报表谷用电量报错')
siteVersion.addVersion('0.3.7_20181204','修复能源费用返回数据增加费用列')
siteVersion.addVersion('0.3.8_20181205','能源费用返回数据保留一位小数')
siteVersion.addVersion('0.3.9_20181206','升级报警接口')
siteVersion.addVersion('0.3.10_20181207','升级warning接口')
siteVersion.addVersion('0.3.11_20181207','升级warning接口2')
siteVersion.addVersion('0.3.12_20181214','升级语音播放接口')
siteVersion.addVersion('0.3.13_20181214','升级规则报警接口')
siteVersion.addVersion('0.3.14_20181222','解决添加点的搜索不到的bug')
siteVersion.addVersion('0.3.15_20181224','解决facotry导入报警配置高低限type的bug')
siteVersion.addVersion('0.3.16_20100103','增加报警的云传送机制')
siteVersion.addVersion('0.3.17_20100104','修正报警的云传送机制')
siteVersion.addVersion('0.3.18_20100109','新增注册码剩余天数接口')
siteVersion.addVersion('0.3.19_20190109','新增数据库结构代码')
siteVersion.addVersion('0.3.20_20190110','修复全局配置接口参数为{}时返回空的bug')
siteVersion.addVersion('0.3.21_20190115','修复注册机器码bug')
siteVersion.addVersion('0.3.22_20190115','修复日志bug')
siteVersion.addVersion('0.3.23_20190121','修复实时数据的bug')
siteVersion.addVersion('0.3.24_20190208','修复实时报警的bug')
siteVersion.addVersion('0.3.25_20190224','增加简易计算点在点表中的支持')
siteVersion.addVersion('0.3.26','表达式的功能改进')
siteVersion.addVersion('0.3.27','报表改进')
siteVersion.addVersion('0.3.28','报表查询后台改进')
siteVersion.addVersion('0.3.29','增加上传操作记录的日志')
siteVersion.addVersion('0.3.30','增加页面权限支持')
siteVersion.addVersion('0.3.31','增加后台版本支持')
siteVersion.addVersion('0.3.32','页面权限bug修复')
siteVersion.addVersion('0.3.33','增加报表api及报表查询接口')
siteVersion.addVersion('0.3.33','多线程计算点')
siteVersion.addVersion('0.3.34','計算點後臺升級')
siteVersion.addVersion('0.3.35','計算點增加设置记录进logic_operation表')
siteVersion.addVersion('0.3.36','报表生成时的时间记录')
siteVersion.addVersion('0.3.37','修复报表查询bug')
siteVersion.addVersion('0.3.38','PIL库')
siteVersion.addVersion('0.3.39','去掉写数据库的逻辑过频繁')
siteVersion.addVersion('0.3.40','增加历史数据时间范围删除和补数')
siteVersion.addVersion('0.3.41','升级accum公式')
siteVersion.addVersion('0.4.1','升级支持报警配置的详细解释脚本')
siteVersion.addVersion('0.4.2','规则报警记录')
siteVersion.addVersion('0.4.3','报警扫描升级')
siteVersion.addVersion('0.4.4','去冗余LOG')
siteVersion.addVersion('0.4.5','增加cors支持')
siteVersion.addVersion('0.4.6','用户页面权限bug修复')
siteVersion.addVersion('0.4.7','虚拟点计算点重新载入前清空，否则将重复计算很多次')
siteVersion.addVersion('0.4.8','getPlant接口checkbox字体颜色格式修改')
siteVersion.addVersion('0.4.9','getSystemEquipmentPage图片加前缀：template/')
siteVersion.addVersion('0.4.10','增加项目管理模块')
siteVersion.addVersion('0.4.11','增加get_today_data_delta')
siteVersion.addVersion('0.4.12','增加unit01中的dompysite的版本、重启次数、重启时间等记录')
siteVersion.addVersion('0.4.13','自动生成点表和点名翻译接口修改')
siteVersion.addVersion('0.4.14','自动生成点表和点名翻译接口修改等更新')
siteVersion.addVersion('0.4.15','日程bug修复')
siteVersion.addVersion('0.4.16','模板设备text 小数位修复')
siteVersion.addVersion('0.4.17','自动生成点名更新')
siteVersion.addVersion('0.4.18','增加/logic/setDrawing 和 /logic/getDrawing 接口')
siteVersion.addVersion('0.4.19','点名翻译更新')
siteVersion.addVersion('0.4.20','增加给logic后台的接口')
siteVersion.addVersion('0.4.21','新增策略接口')
siteVersion.addVersion('0.4.22','云剥离，同时修复清除磁盘log的bug')
siteVersion.addVersion('0.4.23','计算型虚拟点读取时会过滤掉get_api型的点的bug')
siteVersion.addVersion('0.4.24','getSyslogicList接口修改')
siteVersion.addVersion('0.4.25','getPlant接口支持模板设备从属图标')
siteVersion.addVersion('0.4.26','getPlant接口rotateAngle改为integer')
siteVersion.addVersion('0.4.27','getPlant接口children添加id')
siteVersion.addVersion('0.4.28','getPlant接口children修改id')
siteVersion.addVersion('0.4.29','getPlant接口animationList更新')
siteVersion.addVersion('0.4.30','getPlant接口模板设备从属图标坐标偏差处理')
siteVersion.addVersion('0.4.31','增加心跳在线机制')
siteVersion.addVersion('0.4.32','修复point功能')
siteVersion.addVersion('0.4.33','32废版本修复')
siteVersion.addVersion('0.4.34','增加计算去年同时间的值的api')
siteVersion.addVersion('0.4.35','修复license字段没有还能让进入的bug')
siteVersion.addVersion('0.4.36','升级get_data_at_time')
siteVersion.addVersion('0.4.37','升级transferPointName')
siteVersion.addVersion('0.4.38','修改getPlant接口')
siteVersion.addVersion('0.4.39','升级remove_history_data')
siteVersion.addVersion('0.4.40','支持报警的点值字段')
siteVersion.addVersion('0.4.41','增加日程V2接口')
siteVersion.addVersion('0.4.42','日程V2接口修改')
siteVersion.addVersion('0.4.43','日程V2接口修改')
siteVersion.addVersion('0.4.44','日程V2接口修改')
siteVersion.addVersion('0.4.45','getPlant接口修改')
siteVersion.addVersion('0.4.45','getPlant接口支持从属图标旋转角度与主设备一致')
siteVersion.addVersion('0.4.46','报警扩展字段')
siteVersion.addVersion('0.4.47','报警扩展字段修复脚本导入不支持的bug')
siteVersion.addVersion('0.4.48','报警扩展字段修复脚本导入不支持的bug')
siteVersion.addVersion('0.4.49','增加了历史数据备份机制')
siteVersion.addVersion('0.4.50','增加了condition_last_minutes api')
siteVersion.addVersion('0.4.51','导入历史数据时支持表格首行首列是pointtime')
siteVersion.addVersion('0.4.52','月计算api修复bug')
siteVersion.addVersion('0.4.53','增加update_syslogic接口')
siteVersion.addVersion('0.4.54','report tool接口修改')
siteVersion.addVersion('0.4.55','增加get_data_is_not_changing api')
siteVersion.addVersion('0.4.56','修复get_data_is_not_changing api')
siteVersion.addVersion('0.4.57','增加reportTool接口')
siteVersion.addVersion('0.4.58','reportTool接口0点处理')
siteVersion.addVersion('0.4.59','excel生成的每个单元格的log记录')
siteVersion.addVersion('0.4.60','增加backupMysql函数')
siteVersion.addVersion('0.4.61','修改backupMysql函数')
siteVersion.addVersion('0.4.62','修改backupMysql函数')
siteVersion.addVersion('0.4.63','修改backupMysql函数')
siteVersion.addVersion('0.4.64','修改backupMysql函数')
siteVersion.addVersion('0.4.65','排查backupMysql问题')
siteVersion.addVersion('0.4.66','backupmysql函数修改')
siteVersion.addVersion('0.4.67','backupmysql独立出来')
siteVersion.addVersion('0.4.68','backupmysql独立出来')
siteVersion.addVersion('0.4.69','backupMysql修改')
siteVersion.addVersion('0.4.70','报表字符串bug修复')
siteVersion.addVersion('0.4.71','/analysis/get_pointList_from_s3db 接口增加点的最大值最小值')
siteVersion.addVersion('0.4.72','/analysis/get_pointList_from_s3db 接口修改返回格式')
siteVersion.addVersion('0.4.73','修改/get_point_info_from_s3db 接口')
siteVersion.addVersion('0.4.74','get_today_delta零点机制修复')
siteVersion.addVersion('0.4.75','增加updateLogicFileInProject接口，经手人：Mark')
siteVersion.addVersion('0.4.76','修复mysql log表清理的功能问题')
siteVersion.addVersion('0.4.77','修复多个api计算点and时的报错')
siteVersion.addVersion('0.4.78','domlog数据库支持')
siteVersion.addVersion('0.4.79','修改get_plant中layer小于0的元素获取问题')
siteVersion.addVersion('0.4.80','增加env的增删改查接口')
siteVersion.addVersion('0.4.81','修改/env/get接口')
siteVersion.addVersion('0.4.82','增加/env/import  /env/saveContent接口')
siteVersion.addVersion('0.4.83','修改/env/getAll 接口，不返回enalbed = 0的记录')
siteVersion.addVersion('0.4.84','增加场景日程接口')
siteVersion.addVersion('0.4.85','增加设置值时的脚本')
siteVersion.addVersion('0.4.86','增加模式管理接口')
siteVersion.addVersion('0.4.87','增加万年历管理接口')
siteVersion.addVersion('0.4.88','增加point_exists api')
siteVersion.addVersion('0.4.89','修复查询策略log接口')
siteVersion.addVersion('0.4.90','增加downloadSampleData接口')
siteVersion.addVersion('0.4.91','增加/mode/edit接口')
siteVersion.addVersion('0.4.92','修改mysql实例化问题')
siteVersion.addVersion('0.4.93','get_plant接口system_equipment的子设备添加linkInfo')
siteVersion.addVersion('0.4.94','get_plant接口标准设备增加占位符')
siteVersion.addVersion('0.4.95','增加addModeToCalendar接口')
siteVersion.addVersion('0.4.96','增加getCalendarWithMode')
siteVersion.addVersion('0.4.97','addModeToCalendar接口修改')
siteVersion.addVersion('0.4.98','getCalendarWithMode修改')
siteVersion.addVersion('0.4.99','removeModeFromCalendar接口添加')
siteVersion.addVersion('0.4.100','get_plant_pagedetails访客权限修改')
siteVersion.addVersion('0.4.101','get_plant接口gage增加layer字段')
siteVersion.addVersion('0.4.102','增加getTodayModeList接口')
siteVersion.addVersion('0.4.103','修复模式接口的一些bug')
siteVersion.addVersion('0.4.104','修改批量添加模式至日历接口')
siteVersion.addVersion('0.4.105','修改getSystemEquipmentPage接口')
siteVersion.addVersion('0.4.106','修改getContent接口')
siteVersion.addVersion('0.4.107','增加mode/editContent接口')
siteVersion.addVersion('0.4.108','mode/addContent接口修改')
siteVersion.addVersion('0.4.109','mode/editContent接口修改')
siteVersion.addVersion('0.4.110','mode/editContent, mode/addContent接口修改')
siteVersion.addVersion('0.4.111','模式接口修改')
siteVersion.addVersion('0.4.112','reportTool增加get_day_delta_last_month')
siteVersion.addVersion('0.4.113','修改/mode/editContent')
siteVersion.addVersion('0.4.114','修改：场景excel导入时直接覆盖；场景名称重名检查；logo多个图片获取')
siteVersion.addVersion('0.4.115','修改：模式管理中场景按时间降序排列')
siteVersion.addVersion('0.4.116','修改：批量绑定模式；模式添加内容时出发值修改')
siteVersion.addVersion('0.4.117','修改：场景删除接口')
siteVersion.addVersion('0.4.118','修改：get_plant接口，为gages增加type和path')
siteVersion.addVersion('0.4.119','siteinterface\static\images增加15张图片')
siteVersion.addVersion('0.4.120','get_plant 模板图元部分升级')
siteVersion.addVersion('0.4.121','增加getPngImageList接口')
siteVersion.addVersion('0.4.122','bug修改：/calendar/batchAddModeToCalendar')
siteVersion.addVersion('0.4.123','bug修改：/mode/create 模式名称重复性检查')
siteVersion.addVersion('0.4.124','增加API run_num_count')
siteVersion.addVersion('0.4.125','getSystemEquipmentPage接口提速更新')
siteVersion.addVersion('0.4.126','百度AI语音调用')
siteVersion.addVersion('0.4.127','siteinterface\static\images增加图片liquidLevelPoint.png')
siteVersion.addVersion('0.4.128','更换图片')
siteVersion.addVersion('0.4.129','getPngImageList解口中将返回的列表中将logo_small.png移除')
siteVersion.addVersion('0.4.130','mode增加接口一次性读取所有及active信息')
siteVersion.addVersion('0.4.131','key serial过短')
siteVersion.addVersion('0.4.132','bug修改：env/get接口释义字段错误')
siteVersion.addVersion('0.4.133','bug修改：getRequestNo问题修复')
siteVersion.addVersion('0.4.134','get_plant gages增加字体颜色和大小')
siteVersion.addVersion('0.4.135','增加隔日时间处理；get_plant接口增加水流形状')
siteVersion.addVersion('0.4.136','优化批量写入的数据库操作，大量的分批进行')
siteVersion.addVersion('0.4.137','siteinterface\static\images增加图片')
siteVersion.addVersion('0.4.138','模式增加安全机制')
siteVersion.addVersion('0.4.139','修改 get_user_id_by_name')
siteVersion.addVersion('0.4.140','报表功能增加API: get_day_delta_at_month_this_year')
siteVersion.addVersion('0.4.141','增加API：get_current_active_mode_name')
siteVersion.addVersion('0.4.142','模式删除接口修改')
siteVersion.addVersion('0.4.143','新建和修改模式名称时对模式名称进行前后空格去除处理')
siteVersion.addVersion('0.4.144','登录认证机制导致1-10号内登录需验证码bug修复')
siteVersion.addVersion('0.4.145','get_plant接口增加text背景框样式')
siteVersion.addVersion('0.4.146','修复实时请求里脚本评估一个不通过全部无法计算的bug')
siteVersion.addVersion('0.4.147','修复模板id不对应时显示的bug')
siteVersion.addVersion('0.4.148','增加domSpaceClean进程支持')
siteVersion.addVersion('0.4.149','支持批量绑定模式时的指定周几')
siteVersion.addVersion('0.4.150','/env/saveContent支持点名列表为空时的保存')
siteVersion.addVersion('0.4.151','增加api: stats_running_count')
siteVersion.addVersion('0.4.152','get_plant增加dataFix')
siteVersion.addVersion('0.4.153',"增加/fix/add  /fix/remove 接口")
siteVersion.addVersion('0.4.154',"增加/fix/modify  /fix/getById 接口")
siteVersion.addVersion('0.4.155',"增加接口 /weather/getTodayWeatherInfo")
siteVersion.addVersion('0.4.156',"增加api: is_point_now_on_in_schedule, is_point_now_off_in_schedule")
siteVersion.addVersion('0.4.157',"增加api: random_between_start_stop")
siteVersion.addVersion('0.4.158',"增加api: get_avg_value")
siteVersion.addVersion('0.4.159',"增加接口： /fix/insertImage")
siteVersion.addVersion('0.4.160',"接口/energy/feeReportGen 处理")
siteVersion.addVersion('0.4.161',"/fix/insertImage升级支持多图上传")
siteVersion.addVersion('0.4.162',"增加接口： /fix/downloadFixContentInPDF")
siteVersion.addVersion('0.4.163',"修改接口： /fix/downloadFixContentInPDF")
siteVersion.addVersion('0.4.164',"增加接口： /fix/downloadFixContentInExcel")
siteVersion.addVersion('0.4.165',"紧急注释PyQt4")
siteVersion.addVersion('0.4.166',"增加接口： /fix/getByPeriod")
siteVersion.addVersion('0.4.167',"修改接口： /fix/getByPeriod")
siteVersion.addVersion('0.4.168',"报修接口增加title")
siteVersion.addVersion('0.4.169',"增加接口：/fix/downloadFixContentInDocx   /fix/keywordSearch")
siteVersion.addVersion('0.4.170',"修改接口：/fix/downloadFixContentInDocx")
siteVersion.addVersion('0.4.171',"增加接口：/fix/downloadFixContentInPdf")
siteVersion.addVersion('0.4.172',"增加接口：/get_plant/<proj>/<pageid>接口systemEquipment中增加texts")
siteVersion.addVersion('0.4.173',"增加接口：/dataSample/getIO 修改")
siteVersion.addVersion('0.4.174',"增加接口：/env/export ")
siteVersion.addVersion('0.4.175',"接口修改：/get_plant 增加矩形，rectangle")
siteVersion.addVersion('0.4.176',"接口修改：/get_plant 标注设备text的坐标换算")
siteVersion.addVersion('0.4.177',"接口修改：/get_plant 标注设备文本id去重处理")
siteVersion.addVersion('0.4.178',"接口修改：/calendar/batchAddModeToCalendar")
siteVersion.addVersion('0.4.179',"接口修改：/calendar/batchAddModeToCalendar")
siteVersion.addVersion('0.4.180',"接口修改：/weather/getTodayWeatherInfo")
siteVersion.addVersion('0.4.181',"天气图标提交")
siteVersion.addVersion('0.4.182',"API修改：get_day_delta_last_month")
siteVersion.addVersion('0.4.183',"接口修改：warning/downloadHistoryFile")
siteVersion.addVersion('0.4.184',"接口修改：/warningConfig/addRule")
siteVersion.addVersion('0.4.185',"接口修改：/mode/addContent")
siteVersion.addVersion('0.4.186',"backgroupImg打包 ")
siteVersion.addVersion('0.4.187',"接口升级：/fix/downloadFixContentInExcel")
siteVersion.addVersion('0.4.188',"接口升级：/fix/getByPeriod")
siteVersion.addVersion('0.4.189',"接口增加：/fix/getAll ")
siteVersion.addVersion('0.4.190',"接口修改：/fix/downloadFixContentInExcel ")
siteVersion.addVersion('0.4.191',"接口修改：/get_plant text增加单位字段")
siteVersion.addVersion('0.4.192',"domShutdown 增加domSiemenseTCPCore.exe ")
siteVersion.addVersion('0.4.193',"domIoTControllerManager接口支持")
siteVersion.addVersion('0.4.194',"domIoTControllerManager接口支持修改")
siteVersion.addVersion('0.4.195',"/fix/getAll升级")
siteVersion.addVersion('0.4.196',"domIoTControllerManager相关接口升级")
siteVersion.addVersion('0.4.197',"get_thismonth_delta升级")
siteVersion.addVersion('0.4.198',"domIoT接口修改")
siteVersion.addVersion('0.4.199',"增加domIoT时间同步接口")
siteVersion.addVersion('0.4.200',"get_thismonth_delta修改")
siteVersion.addVersion('0.4.201',"domiot接口修改")
siteVersion.addVersion('0.4.202',"domiot接口修改 ")
siteVersion.addVersion('0.4.203',"weather参数修改 ")
siteVersion.addVersion('0.4.204',"模式时间排序，用户权限内的空组去除内容 ")
siteVersion.addVersion('0.4.205',"模式时间排序，用户权限内的空组去除内容bug ")
siteVersion.addVersion('0.4.206',"重新打包")
siteVersion.addVersion('0.4.207',"增加日期api")
siteVersion.addVersion('0.4.208',"去清除log机制")
siteVersion.addVersion('0.4.209',"支持多模板图片解压 ")
siteVersion.addVersion('0.4.210',"打包error ")
siteVersion.addVersion('0.4.211',"多模板后台支持")
siteVersion.addVersion('0.4.212',"多模板解压图片修改")
siteVersion.addVersion('0.4.213',"getSystemEquipmentPage接口修改")
siteVersion.addVersion('0.4.214',"getSystemEquipmentPage接口修改")
siteVersion.addVersion('0.4.215',"getSystemEquipmentPage接口修改")
siteVersion.addVersion('0.4.216',"操作记录深入细化来源")
siteVersion.addVersion('0.4.217',"/user/add 接口修改")
siteVersion.addVersion('0.4.218'," 场景点表导入支持返回无效点名；历史数据接口升级支持返回脚本历史数据")
siteVersion.addVersion('0.4.219',"增加get_hour_data_delta API")
siteVersion.addVersion('0.4.220',"/mode/editContent 接口修改")
siteVersion.addVersion('0.4.221',"/weather/getForcastWeatherInfo 接口修改")
siteVersion.addVersion('0.4.222',"/getSystemEquipmentPage 接口修改")
siteVersion.addVersion('0.4.223',"增加接口：/mode/getTodayModeListByTypes")
siteVersion.addVersion('0.4.224',"修改接口：/mode/getTodayModeListByTypes")
siteVersion.addVersion('0.4.225',"修改接口：/mode/getTodayModeListByTypes、 /calendar/getCalendarWithMode")
siteVersion.addVersion('0.4.226',"指令输出位置更改")
siteVersion.addVersion('0.4.227',"增加接口：/mode/copyOneMode")
siteVersion.addVersion('0.4.228',"修改接口：/mode/copyOneMode")
siteVersion.addVersion('0.4.229',"修改接口：/calendar/getCalendarWithMode")
siteVersion.addVersion('0.4.230',"基础数据库接口加入None的意外机制处理")
siteVersion.addVersion('0.4.231',"操作记录修补至磁盘写入")
siteVersion.addVersion('0.4.232',"增加接口：/env/getAllTags; /env/getEnvByTags")
siteVersion.addVersion('0.4.233',"修改接口（增加排序功能）：/env/getAllTags  getTodayModeListOfTypes")
siteVersion.addVersion('0.6.33',"实时请求接口的None简化")
siteVersion.addVersion('0.6.34',"/calendar/getCalendarWithMode  接口中增加天气信息")
siteVersion.addVersion('0.6.35',"增加接口：/obix/setRealtimeDataAndGetPointsToWrite")
siteVersion.addVersion('0.6.36',"增加ThirdParty日志")
siteVersion.addVersion('0.6.37',"增加api: get_today_data_avg_in_time_range")
siteVersion.addVersion('0.6.38',"修改api: get_today_data_avg_in_time_range")
siteVersion.addVersion('0.6.39',"增加redis支持")
siteVersion.addVersion('0.6.40',"增加redis支持，读取点清单时bug")
siteVersion.addVersion('0.6.41',"增加api:get_date_string_today")
siteVersion.addVersion('0.6.42',"修复API问题")
siteVersion.addVersion('0.6.43',"测试报表生成问题")
siteVersion.addVersion('0.6.44',"支持报警音static目录")
siteVersion.addVersion('0.6.45',"增加api: get_avg_value_running")
siteVersion.addVersion('0.6.46',"支持百度mp3")
siteVersion.addVersion('0.6.47',"修改接口： /get_realtimedata")
siteVersion.addVersion('0.6.48',"logixCore接口支持")
siteVersion.addVersion('0.6.49',"logixCore接口升級")
siteVersion.addVersion('0.6.50',"logixCore接口升級")
siteVersion.addVersion('0.6.51',"增加接口：/operation/logicRecordOutput")
siteVersion.addVersion('0.6.52',"增加version接口")
siteVersion.addVersion('0.6.53',"get_plant time log")
siteVersion.addVersion('0.6.54',"增加接口：/logix/clearOutputTable")
siteVersion.addVersion('0.6.55',"增加接口：/pointCalculation/calHistory")
siteVersion.addVersion('0.6.56',"修改接口：/pointCalculation/calHistory")
siteVersion.addVersion('0.6.57',"修改接口：/pointCalculation/calHistory, 延长取值时间段")
siteVersion.addVersion('0.6.58',"增加接口：/scriptCalculation/calHistory   /scriptCalculation/insertHistory")
siteVersion.addVersion('0.6.59',"排查写值")
siteVersion.addVersion('0.6.60',"计算点增加线程计算容量")
siteVersion.addVersion('0.6.61',"去掉不必要的log print")
siteVersion.addVersion('0.6.62',"接口修改：/scriptCalculation/insertHistory")
siteVersion.addVersion('0.6.63',"增加报表单独日志")
siteVersion.addVersion('0.6.64',"增加redis历史数据缓存")
siteVersion.addVersion('0.6.65',"增加redis历史数据缓存继续优化")
siteVersion.addVersion('0.6.66',"增加redis历史数据缓存继续优化2")
siteVersion.addVersion('0.6.67',"增加redis历史数据缓存继续优化3")
siteVersion.addVersion('0.6.68',"增加redis历史数据缓存继续优化4")
siteVersion.addVersion('0.6.69',"/getSystemEquipment 增加rectangles")
siteVersion.addVersion('0.6.70',"/strategy/getThreadDetailList 增加策略运行状态")
siteVersion.addVersion('0.6.71',"增加禁用实时计算虚拟点功能")
siteVersion.addVersion('0.6.72',"word报表功能")
siteVersion.addVersion('0.6.73',"报表接口修改")
siteVersion.addVersion('0.6.74',"增加连接池的ini配置支持")
siteVersion.addVersion('0.6.75',"增加图片解压接口")
siteVersion.addVersion('0.6.76',"增加对点名页面关系的报警查询")
siteVersion.addVersion('0.6.77',"增加对点名页面关系的报警查询, 数组兼容bug")
siteVersion.addVersion('0.6.78',"增加对点名页面关系的报警查询, 数组兼容bug")
siteVersion.addVersion('0.6.79',"accum_point增加对历史补数支持")
siteVersion.addVersion('0.6.80',"/get_plant 支持直线")
siteVersion.addVersion('0.6.81',"增加api:get_work_days_of_this_month")
siteVersion.addVersion('0.6.82',"增加api:get_days_of_this_month")
siteVersion.addVersion('0.6.83',"/weather/getTodayWeatherInfo 增加temp")
siteVersion.addVersion('0.6.84',"增加接口：/fdditem/getFaultInfo")
siteVersion.addVersion('0.6.84',"支持多边形")
siteVersion.addVersion('0.6.85',"故障管理支持")
siteVersion.addVersion('0.6.86',"故障管理支持")
siteVersion.addVersion('0.6.87',"接口增加：/fdd/getGroupMembersOfAdmin,  /fdd/addFault,  /fdd/processFault")
siteVersion.addVersion('0.6.88',"接口修改：/fdd/query")
siteVersion.addVersion('0.6.89',"接口修改：/fdd/addFault,  /fdd/getGroupMembersOfAdmin")
siteVersion.addVersion('0.6.90',"故障管理接口修改")
siteVersion.addVersion('0.6.91',"/fdd/processFault 修改")
siteVersion.addVersion('0.6.92', "支持get_last_week_data_at_same_time, get_yesterday_data_at_same_time等快速数据api")
siteVersion.addVersion('0.6.93', "接口增加：/fdd/addMaintainanceFault")
siteVersion.addVersion('0.6.93', "故障管理接口修改：将创建时间作为故障的查询时间")
siteVersion.addVersion('0.6.94', "添加故障接口修改")
siteVersion.addVersion('0.6.95', "/fdd/addMaintainanceFault 接口修改")
siteVersion.addVersion('0.6.96', "api利用redis优化")
siteVersion.addVersion('0.6.97', "接口修改：/get_plant rectangle增加属性")
siteVersion.addVersion('0.6.98', "接口修改：/fdd/statistic")
siteVersion.addVersion('0.6.99', "接口修改：/get_plant 接口增加placeHolder")
siteVersion.addVersion('0.7.0', "模式接口修改：mode_detail中增加actionOnce字段后的兼容性修改")
siteVersion.addVersion('0.7.1', "修改接口：/mode/editContent  增加接口：/logic/updateHealthLog")
siteVersion.addVersion('0.7.2', "接口修改：/logic/updateHealthLog")
siteVersion.addVersion('0.7.3', "get_plant防止图片不存在的机制")
siteVersion.addVersion('0.7.4', "/get_plant   /getSystemEquipmentPage增加图片无法显示处理机制")
siteVersion.addVersion('0.7.5', "/get_plant equipments SQL查询优化")
siteVersion.addVersion('0.7.6', "/mode/addContent 增加点名存在性判断")
siteVersion.addVersion('0.7.7', "修改/get_realtimedata接口")
siteVersion.addVersion('0.7.8', "增加moxa支持接口")
siteVersion.addVersion('0.7.9', "接口修改：/get_plant")
siteVersion.addVersion('0.7.10', "接口修改：/get_plant")
siteVersion.addVersion('0.7.11', "增加接口：/fdd/flow")
siteVersion.addVersion('0.7.12', "修改接口：/get_realtimedata")
siteVersion.addVersion('0.7.13', "增加：启动时将所有电信息存入redis")
siteVersion.addVersion('0.7.14', "增加：/getPointInfoFromRedis")
siteVersion.addVersion('0.7.15', "修改接口：/warningConfig/add")
siteVersion.addVersion('0.7.16', "修改接口：/get_plant rectangles增加内容")
siteVersion.addVersion('0.7.17', " 修改接口：/get_plant 兼容rectangles里面的点名列表")
siteVersion.addVersion('0.7.18', " 修改API：get_thismonth_delta")
siteVersion.addVersion('0.7.19', "接口升级：/operation/logicRecordOutput增加从文件查询机制")
siteVersion.addVersion('0.7.20', "接口升级：/get_history_data_padded")
siteVersion.addVersion('0.7.21', "接口增加：/serviceData/getRealtime  /serviceData/getHistory")
siteVersion.addVersion('0.7.22', "接口修改：/serviceData/getRealtime  /serviceData/getHistory")
siteVersion.addVersion('0.7.23', "reportTool 增加import calendar")
siteVersion.addVersion('0.7.24', "增加接口：/serviceData/monthlyStatics")
siteVersion.addVersion('0.7.25', "修改 get_history_data_padded方法中filter作为形参传入")
siteVersion.addVersion('0.7.26', "增加 domhost 监视")
siteVersion.addVersion('0.7.27', "增加模式type变动后的处理")
siteVersion.addVersion('0.7.28', "修复/get_plant_pagedetails 的分组顺序不对的问题")
siteVersion.addVersion('0.7.29', "增加接口：/mode/batchDelete; Redis连接增加timeout")
siteVersion.addVersion('0.7.30', "增加api: is_point_will_on_in_schedule, is_point_will_off_in_    schedule")
siteVersion.addVersion('0.7.31', "增加接口：/warningConfig/export")
siteVersion.addVersion('0.7.32', "增加接口：/calendar/batchRemoveModeFromCalendar")
siteVersion.addVersion('0.7.33', "增加接口：/report/delete")
siteVersion.addVersion('0.7.34', "/getSystemEquipmentPage 接口修改")
siteVersion.addVersion('0.7.35', "增加接口：/calendar/batchRemoveModeFromCalendarThisMonth")
siteVersion.addVersion('0.7.36', "修改接口：/calendar/batchRemoveModeFromCalendarThisMonth")
siteVersion.addVersion('0.7.37', "修改接口：/fdd/statistic 增加逾期率和解决率计算")
siteVersion.addVersion('0.7.38', "实时数据请求接口中去掉多余的数据仿真代码-old code from lxy")
siteVersion.addVersion('0.7.39', "1-启动时检查config.ini中的项目名称若无则填入MAC地址；2-修改接口/weather/requestAndSaveCalendar")
siteVersion.addVersion('0.7.40', "启动时检查config.ini中的项目名称并填入MAC地址修改")
siteVersion.addVersion('0.7.41', "is_point_will_on_in_schedule,  is_point_will_off_in_schedule 修改")
siteVersion.addVersion('0.7.42', "修改api：get_thismonth_data_avg, 增加api: get_thismonth_daily_data_delta_at_hour")
siteVersion.addVersion('0.7.43', "修改/get_operation_log")
siteVersion.addVersion('0.7.44', "/get_plant rectangles点名列表中增加注释和单位")
siteVersion.addVersion('0.7.45', "/get_history_data_padded 修改（请求时排序）")
siteVersion.addVersion('0.7.46', "/get_plant 修改：增加导航配置、矩形增加小数位")
siteVersion.addVersion('0.7.47', "/get_plant 修改：page增加navJsonConfig")
siteVersion.addVersion('0.7.48', "/mode/copyOneMode 执行一次/持续执行bug修改")
siteVersion.addVersion('0.7.49', "/getPageType 增加navJsonConfig")
siteVersion.addVersion('0.7.50', "增加接口：/getCurrentSystemResource")
siteVersion.addVersion('0.7.51', "修复节假日误判")
siteVersion.addVersion('0.7.52', "接口修改：/getCurrentSystemResource")
siteVersion.addVersion('0.7.53', "增加接口： /system/restartOS   /system/clearLog")
siteVersion.addVersion('0.7.54', "修改接口：/report/getReportHistory")
siteVersion.addVersion('0.7.55', "修改接口：/get_operation_log")
siteVersion.addVersion('0.7.56', "startProcess 函数修改：详细化exception error 信息")
siteVersion.addVersion('0.7.57', "startProcess 函数修改")
siteVersion.addVersion('0.7.58', "增加接口：/strategy/getLogInfoOfOneDayZipped    /strategy/getLatestRoundLogInfo")
siteVersion.addVersion('0.7.59', "修改接口：/strategy/getLatestRoundLogInfo   增加接口：/log/getProcessLogInfoOfOneDay"  )
siteVersion.addVersion('0.7.60', "增加虚拟点公式修改接口、公式测试接口增加debug信息"  )
siteVersion.addVersion('0.7.61', "增加接口：/equipment/getRoomEquipmentListAndStatus"  )
siteVersion.addVersion('0.7.62', "改进接口：/pointData/getRealtimeWithPages"  )
siteVersion.addVersion('0.7.62', "改进接口：/pointData/getRealtimeWithPages"  )
siteVersion.addVersion('0.7.63', "修改接口：/equipment/getRoomEquipmentListAndStatus"  )
siteVersion.addVersion('0.7.64', "完善M1查询"  )
siteVersion.addVersion('0.7.65', "完善重启core进程中domSiemenseTCPCore"  )
siteVersion.addVersion('0.7.66', "升级接口： /getCurrentSystemResource")
siteVersion.addVersion('0.7.67', "升级接口： /getSystemEquipmentPage升级")
siteVersion.addVersion('0.7.68', "升级接口： /license机器码升级")
siteVersion.addVersion('0.7.69', "升级接口： /analysis/get_point_info_from_s3db")
siteVersion.addVersion('0.7.70', "增加API： get_date_string_yesterday")
siteVersion.addVersion('0.7.71', "增加接口：  /calendar/getModeOfTypeOnCertainDate")
siteVersion.addVersion('0.7.72', "修改接口：  /report/genExcelReportByTemplate")
siteVersion.addVersion('0.7.73', "增加API：  get_this_month_data_sum")
siteVersion.addVersion('0.7.74', "修改接口： /pointData/getRealtimeWithPages")
siteVersion.addVersion('0.8.1', "机器码升级导致的内存泄漏问题解决，注意0.7.68后的版本均有重大漏洞，需升级到0.8")
siteVersion.addVersion('0.8.2', "/get_plant接口升级：rectangles内点类型增加type")
siteVersion.addVersion('0.8.3', "修复 /pointData/getRealtimeWithPages 传入空关键词列表后返回结果为空的bug")
siteVersion.addVersion('0.8.4', "启动时更新心跳，防止有时启动过程中被domhost杀掉")
siteVersion.addVersion('0.9.1', "功能较大改动：增加数据回归模型")
siteVersion.addVersion('0.9.2', "【重大漏洞版本】license支持改进")
siteVersion.addVersion('0.9.3', "license支持改进")
siteVersion.addVersion('0.9.4', "改进excel报表曲线颜色")
siteVersion.addVersion('0.9.5', "增加接口：/project/getWorkConditionByProjectTimeRange")
siteVersion.addVersion('0.9.6', "增加对predictModel目录位置修复")
siteVersion.addVersion('0.9.7', "增加tool导入导出excel")
siteVersion.addVersion('0.9.8', "修改接口：/tool/ConvertTableToExcel   /tool/ConvertExcelToTable")
siteVersion.addVersion('0.9.9', "增加insert_history_data_mul")
siteVersion.addVersion('0.9.10', "修改接口：insert_history_data_mul")
siteVersion.addVersion('0.9.11', "修改接口：/tool/ConvertExcelToTable")
siteVersion.addVersion('0.9.12', "增加pool size")
siteVersion.addVersion('0.9.13', "升级/version")
siteVersion.addVersion('0.9.14', "增加API: get_date_string_this_month_of_day, get_data_this_month_at_day_time")
siteVersion.addVersion('0.9.15', "修改pysite对4db的访问，均只读!这样factory可在线修改4db不被影响")
siteVersion.addVersion('0.9.16', "增加API: get_day_time_delta_this_month")
siteVersion.addVersion('0.9.17', "增加API: get_day_time_delta_this_month")
siteVersion.addVersion('0.9.18', "增加API: saveVPointCalculationEquation")
siteVersion.addVersion('0.9.19', "增加历史数据查询的redis支持")
siteVersion.addVersion('0.9.20', "插入历史数据查询的redis支持2")
siteVersion.addVersion('0.9.21', "insert history接口升级")
siteVersion.addVersion('0.9.22', "增加API: get_thisyear_delta_from_month_to_now")
siteVersion.addVersion('0.9.23', "model/predict升级修复array支持")
siteVersion.addVersion('0.9.24', "get_history_data多点被无限大bug的修复")
siteVersion.addVersion('0.9.25', "get_history_data m5优化")
siteVersion.addVersion('0.9.26', "页面缓存优化")
siteVersion.addVersion('0.9.27', "页面权限bug")
siteVersion.addVersion('0.9.28', "updateAllPointInfoIntoRedis接口增加name")
siteVersion.addVersion('0.9.29', "修改get_day_time_delta_this_month")
siteVersion.addVersion('0.9.30', "增加接口/point/getFaultPoints")
siteVersion.addVersion('0.9.31', "百度语音升级")
siteVersion.addVersion('0.9.32', "天气接口升级")
siteVersion.addVersion('0.9.33', "realtimedata接口升級支持請求空數組時返回全部")
siteVersion.addVersion('0.9.34', "serviceData/getRealtime 接口加入IP判断")
siteVersion.addVersion('0.9.35', "/version 增加domModbusClientCore 版本")
siteVersion.addVersion('0.9.36', "修改：/log/getProcessLogInfoOfOneDay")
siteVersion.addVersion('0.9.37', "修改：/log/getProcessLogInfoOfOneDay返回结果")
siteVersion.addVersion('0.9.38', "修改支持多dompysite")
siteVersion.addVersion('0.9.39', "修复condition_last_minutes 的问题")
siteVersion.addVersion('0.9.40', "修改： /core/autoUpdate/<strType>/<strProcessName>/<strUpdateTime>")
siteVersion.addVersion('0.9.41', "修改： /core/autoUpdate/<strType>/<strProcessName>/<strUpdateTime>")
siteVersion.addVersion('0.9.42', "修改： /get_plant 占位符解析做容错处理")
siteVersion.addVersion('0.9.43', "修改： /pointData/getRealtimeWithPages")
siteVersion.addVersion('0.9.44', "增加： /dom/runDomShutdown")
siteVersion.addVersion('0.9.45', "修改：getPointInfoFromS3db_WithRedis")
siteVersion.addVersion('0.9.46', "修改：调试员cx的role")
siteVersion.addVersion('0.9.47', "修改：get_date_string_this_month_of_day")
siteVersion.addVersion('0.9.48', "增加请求记录打印")
siteVersion.addVersion('0.9.49', "修改：/project/getWorkConditionByProjectTimeRange")
siteVersion.addVersion('0.9.50', "knx接口支持")
siteVersion.addVersion('0.9.51', "增加：/config/get")
siteVersion.addVersion('0.9.52', "修改：get_hour_data_delta")
siteVersion.addVersion('0.9.53', "修改：get_hour_data_delta，get_today_data_delta 兼容起始时间自定义")
siteVersion.addVersion('0.9.54', "修改：projectname 初始化为机器码")
siteVersion.addVersion('0.9.55', "修改：/fdd/addMaintainanceFault")
siteVersion.addVersion('0.9.56', "修改：/fdd/query, /fdd/processFault 处理")
siteVersion.addVersion('0.9.57', "修改：/fdd/statistic")
siteVersion.addVersion('0.9.58', "修改：/fdd/processFault")
siteVersion.addVersion('0.9.59', "修改：/fdd/enableFault")
siteVersion.addVersion('0.9.60', "修改：views中warning_get_realtime get意外处理")
siteVersion.addVersion('0.9.61', "升级：故障工单接口")
siteVersion.addVersion('0.9.62', "修改：/fdd/addMaintainanceFault")
siteVersion.addVersion('0.9.63', "修改：故障工单相关接口")
siteVersion.addVersion('0.9.64', "修改：/fdd/addMaintainanceFault, 允许在未输入故障详情、处理人、预计完成时间的前提下也可创建工单")
siteVersion.addVersion('0.9.65', "增加redis更新历史数据接口给core每小时存储时使用")
siteVersion.addVersion('0.9.66', "给get_hour_data_delta增加缓存支持，并修复为计算本小时0分到现在")
siteVersion.addVersion('0.9.67', "【重大漏洞版本】分钟数据近日的进行缓存并利用redis加速")
siteVersion.addVersion('0.9.68', "修复redis死锁")
siteVersion.addVersion('0.9.69', "修复 get_history_data_from_redis 格式问题")
siteVersion.addVersion('0.9.70', "修复 get_history_data_from_redis float格式问题")
siteVersion.addVersion('0.9.71', "修复 get_history_data_from_redis float格式问题2")
siteVersion.addVersion('0.9.72', "修复 get_history_data_from_redis float格式问题3")
siteVersion.addVersion('0.9.73', "修复 get_day_time_delta_this_month中如果结束时间超过当前时间则返回空不做数据库查询")
siteVersion.addVersion('0.9.74', "修复 get_history_data_padded可能传入字符串的兼容")
siteVersion.addVersion('0.9.75', "报表每个报表分一个线程，启动时将解压图片线程化")
siteVersion.addVersion('0.9.76', "去掉pygame, redis识别提前")
siteVersion.addVersion('0.9.77', "get_history_data_from_redis优化")
siteVersion.addVersion('0.9.78', "初始化时redis继续优化")
siteVersion.addVersion('0.9.79', "初始化时redis继续优化")
siteVersion.addVersion('0.9.80', "初始化时redis继续优化")
siteVersion.addVersion('0.9.81', "数据库用户名分开")
siteVersion.addVersion('0.9.81', "数据库用户名分开")
siteVersion.addVersion('0.9.82', "报表生成机制升级")
siteVersion.addVersion('0.9.83', "报表生成机制升级log改进")
siteVersion.addVersion('0.9.84', "redis缓存下载")
siteVersion.addVersion('0.9.85', "redis缓存下载改进")
siteVersion.addVersion('0.9.86', "报表改进")
siteVersion.addVersion('0.9.87', "domUpdate更新接口")
siteVersion.addVersion('0.9.88', "update core_status")
siteVersion.addVersion('0.9.89', "報表第一次不生成設置后再也不生成的bug解決")
siteVersion.addVersion('0.9.90', "報表第一次不生成設置后再也不生成的bug解決V2")
siteVersion.addVersion('0.9.91', "绑定模式时发现模式内容为空则发送警告至云运维中心")
siteVersion.addVersion('0.9.92', "/pointtable/add方法由readonly改成可操作")
siteVersion.addVersion('0.9.93', "增加报表生成状态接口")
siteVersion.addVersion('0.9.94', "报表生成进度接口修改")
siteVersion.addVersion('0.9.95', "修改：/point/getFaultPoints检查redis状态")
siteVersion.addVersion('0.9.96', "增加redis批量清除分钟级数据缓存功能")
siteVersion.addVersion('0.9.97', "增加： /template/ossSyncToLocal接口、/equipment/getInitAssetByIdentity接口")
siteVersion.addVersion('0.9.98', "/serviceData/getRealtime 修改间隔时间")
siteVersion.addVersion('0.9.99', "修改 /fdd/query")
siteVersion.addVersion('0.10.1', "计算点线程机制修改")
siteVersion.addVersion('0.10.2', "计算点线程机制修改2")
siteVersion.addVersion('0.10.3', "/fdd/processFault 增加admin可一键提交")
siteVersion.addVersion('0.10.4', "计算点线程机制修改3")
siteVersion.addVersion('0.10.5', "增加请求ip记录print")
siteVersion.addVersion('0.10.6', "增加nginx端口支持")
siteVersion.addVersion('0.10.7', "增加log")
siteVersion.addVersion('0.10.8', "支持domJob分离")
siteVersion.addVersion('0.10.9', "支持kill logic01-05")
siteVersion.addVersion('0.10.10', "修改：accum_point今日0点取值异常处理")
siteVersion.addVersion('0.10.11', "修改：city_name_convertor")
siteVersion.addVersion('0.10.12', "修改：/equipment/searchAssetTmplDef， 检查设备模板是否存在若不存在则自动创建")
siteVersion.addVersion('0.10.13', "dompysite分离后的心跳bug")
siteVersion.addVersion('0.10.14', "【重大缺陷版本】/status升级支持数据库连接溢出后的处理")
siteVersion.addVersion('0.10.15', "【重大缺陷版本】/fdd/countUserPendingFault容错处理")
siteVersion.addVersion('0.10.16', "【重大缺陷版本】/warning_get_realtime 容错")
siteVersion.addVersion('0.10.17', "/status重大缺陷修复")
siteVersion.addVersion('0.10.18', "增加修改历史数据接口调用的指令记录日志")
siteVersion.addVersion('0.10.19', "增加支持dlt645的接口")
siteVersion.addVersion('0.10.20', "修改/dlt645/clearOutputTable 接口")
siteVersion.addVersion('0.10.21', "增加：接口/getMysqlDiagnosis")
siteVersion.addVersion('0.10.22', "增加：接口/exportAllModeAndEnv")
siteVersion.addVersion('0.10.23', "增加：修改接口：/data/importHistoryDataFile")
siteVersion.addVersion('0.10.24', "修改：接口：/pointTable/importPointTable(支持DEEPLOGIC bacnet点表导入）")
siteVersion.addVersion('0.10.25', "修改：接口：/mode/getAll 无模式时的bug")
siteVersion.addVersion('0.10.26', "修改：接口：/serviceData/getHistory阻塞时间减少至5秒")
siteVersion.addVersion('0.10.27', "增加：接口 /fdd/editUserName  /fdd/editUserPassword")
siteVersion.addVersion('0.10.28', "支持授权的额外limit限制")
siteVersion.addVersion('0.10.29', "修改/get_plant接口bug、/fdd/editUserPassword增加旧密码验证")
siteVersion.addVersion('0.10.30', "故障工单管理中的插入图片接口支持")
siteVersion.addVersion('0.10.31', "/reportTool/genExcelReportByTableData 支持时间列偏移")
siteVersion.addVersion('0.10.32', "修改： /log/getProcessLogInfoOfOneDay   /pointTable/importPointTable")
siteVersion.addVersion('0.10.33', "修改： inssert_history_data 增加重算计算点任务")
siteVersion.addVersion('0.10.34', "warningScan机制修改")
siteVersion.addVersion('0.10.35', "增加: /fdd/export")
siteVersion.addVersion('0.10.36', "修改: /fdd/query")
siteVersion.addVersion('0.10.37', "故障工单接口增加报错后的domcore 和dompysite版本检查")
siteVersion.addVersion('0.10.38', "/mode/getAll bug修改")
siteVersion.addVersion('0.10.39', "修改：/knx/setRealtimeDataAndGetPointsToWrite")
siteVersion.addVersion('0.10.40', "接口支持：ABSLC")
siteVersion.addVersion('0.10.41', "/mode/getAll 接口修改")
siteVersion.addVersion('0.10.42', "增加接口：/getModbusEquipmentInputTableData")
siteVersion.addVersion('0.10.43', "增加redis过期3天限制避免内存过大")
siteVersion.addVersion('0.10.44', "增加mysql连接池溢出后的处理")
siteVersion.addVersion('0.10.45', "修改knx相关接口")
siteVersion.addVersion('0.10.46', "升级knx接口")
siteVersion.addVersion('0.10.47', "增加 /sendTCPPackage")
siteVersion.addVersion('0.10.48', "/sendTCPPackage支持packageList")
siteVersion.addVersion('0.10.49', "deeplogic点表导入修改")
siteVersion.addVersion('0.10.50', "增加： /getDeeplogicRedisConfig")
siteVersion.addVersion('0.10.51', "修改/getReportNameList")
siteVersion.addVersion('0.10.52', "修改:/getDeeplogicRedisConfig")
siteVersion.addVersion('0.10.53', "报表生成bug修改")
siteVersion.addVersion('0.10.54', '修改 fillAllTablesInExcel')
siteVersion.addVersion('0.10.55', 'get_yesterday_data_at_time 增加调试log')
siteVersion.addVersion('0.10.56', '修改cleanDOMDisk')
siteVersion.addVersion('0.10.57', '增加api: get_today_data_begin')
siteVersion.addVersion('0.10.58', '修改：/scriptCalculation/calHistory api中插入actTime处理')
siteVersion.addVersion('0.10.59', '修改：/get_operation_log')
siteVersion.addVersion('0.10.60', '/get_plant, /getSystemEquipmentPage 增加button的预检脚本')
siteVersion.addVersion('0.10.61', '修改：get_data_this_month_at_day_time')
siteVersion.addVersion('0.10.62', '修改：sendTCPPackage')
siteVersion.addVersion('0.10.63', '修改：/get_operation_log')
siteVersion.addVersion('0.10.64', '增加：/startTaskManager')
siteVersion.addVersion('0.10.65', '增加 get_history_data_padded 调试log')
siteVersion.addVersion('0.10.66', '增加 调试log')
siteVersion.addVersion('0.10.67', 'fillAllTablesInExcel 含#的静态文本计算bug处理')
siteVersion.addVersion('0.10.68', '资产管理接口修改')
siteVersion.addVersion('0.10.69', '资产管理增加导入导出接口')
siteVersion.addVersion('0.10.70', '修改资产管理接口')
siteVersion.addVersion('0.10.71', '修改资产管理接口')
siteVersion.addVersion('0.10.72', '修改：get_data_this_month_at_day_time')
siteVersion.addVersion('0.10.73', 'log排查 get_data_this_month_at_day_time')
siteVersion.addVersion('0.10.74', 'get_today_data_at_time、get_yesterday_data_at_time 增加数据缓存')
siteVersion.addVersion('0.10.75', '修改：deepLogic bacnet点翻译为domcore.exe使用的bacnet点')
siteVersion.addVersion('0.10.76', '增加：get_this_year_data_delta')
siteVersion.addVersion('0.10.77', '增加：deepLogic modbus点表导入')
siteVersion.addVersion('0.10.78', '后台报表曲线图生成问题处理')
siteVersion.addVersion('0.10.79', '修改 get_day_delta_this_month')
siteVersion.addVersion('0.10.80', 'RPS：增加客户、订单、仓库管理接口')
siteVersion.addVersion('0.10.81', 'RPS：增加批量导入接口')
siteVersion.addVersion('0.10.82', '修改RPS接口')
siteVersion.addVersion('0.10.83', '修改接口：/importAssetMulti')
siteVersion.addVersion('0.10.84', '修改接口：/updateWarehouse')
siteVersion.addVersion('0.10.85', '增加RFID码管理接口')
siteVersion.addVersion('0.10.86', '修改订单管理接口')
siteVersion.addVersion('0.10.87', '解压图片逻辑改进 - golding')
siteVersion.addVersion('0.10.88', '增加物流接口')
siteVersion.addVersion('0.10.89', '增加进出库接口')
siteVersion.addVersion('0.10.90', '修改：/rps/updateAssetFromContract')
siteVersion.addVersion('0.10.91', '订单、物流、进出库增加审核')
siteVersion.addVersion('0.10.92', '修改 /rps/getContract')
siteVersion.addVersion('0.10.93', 'rps接口增加操作记录')
siteVersion.addVersion('0.10.94', '增加/rps/getAssetOfInOutWarehouse')
siteVersion.addVersion('0.10.95', '修改/rps/addContract')
siteVersion.addVersion('0.10.96', 'insert_history_data_mul中增加容错，避免项目中出现意外日志，观察日志：有收到非法历史数据插入请求')
siteVersion.addVersion('0.10.97', '场景保存时支持事务')
siteVersion.addVersion('0.10.98', '修改rps接口')
siteVersion.addVersion('0.10.99', 'rps订单附件管理接口增加审核机制')
siteVersion.addVersion('0.11.0', 'rps接口增加审核工作流相关接口')
siteVersion.addVersion('0.11.1', '增加/rps/updateRFID   /equipment/searchWithRFID')
siteVersion.addVersion('0.11.2', 'dompysite_debug_get_history过大的日志删除')
siteVersion.addVersion('0.11.3', 'rps接口：订单增加、更新、删除资产加入审核机制')
siteVersion.addVersion('0.11.4', 'rps接口：进出库、物流各接口增加审核机制')
siteVersion.addVersion('0.11.5', 'rps接口：增加RFID,LBS,BEACON 事件获取接口')
siteVersion.addVersion('0.11.6', 'rps 增加报废管理接口')
siteVersion.addVersion('0.11.7', '/rps/updateAssetFromContract 修改')
siteVersion.addVersion('0.11.8', 'rps状态为13时可支持继续添加修改待审核项')
siteVersion.addVersion('0.11.9', '增加：/rps/recallEditAudit')
siteVersion.addVersion('0.11.10', '增加：/rps/terminate')
siteVersion.addVersion('0.11.11', '修改：/rps/getContract')
siteVersion.addVersion('0.11.12', '修改：def add_user 新增用户时可以添加中文名、性别、电话')
siteVersion.addVersion('0.11.13', '修改：/allusers')
siteVersion.addVersion('0.11.14', '修改:validate_user')
siteVersion.addVersion('0.11.15', '修改 /rps/getRpsAuditRecord， 增加/rps/getRpsAttachmentAuditRecord')
siteVersion.addVersion('0.11.16', '修改:解决getRpsAuditRecord方法名错误的问题')
siteVersion.addVersion('0.11.17', '修改:按钮setValue支持逗号分隔的值列表')
siteVersion.addVersion('0.11.18', '修改:增加兩個api:get_data_max_in_day_range 和 get_data_min_in_day_range')
siteVersion.addVersion('0.11.19', '解决/rps/addAttachmentToInOutWarehouse不更改status为13的问题，修改/rps/getAssetOfInOutWarehouse可以拿到每个资产的修改审核项')
siteVersion.addVersion('0.11.20', '解决/rps/getAssetOfInOutWarehouse解决查询时飞掉的问题')
siteVersion.addVersion('0.11.21', '解决/rps/addAttachmentToInOutWarehouse不更改status为13的问题，修改/rps/getAssetOfInOutWarehouse可以拿到每个资产的修改审核项')
siteVersion.addVersion('0.11.22', '解决/rps/updateAssetOfInOutWarehouse解决不更改status为13的问题')
siteVersion.addVersion('0.11.23', '解决模板弹框内按钮setValue')
siteVersion.addVersion('0.11.24', '新增/rps/getNoticeListOfUser，查询一个用户当前是否有需要推送的消息')
siteVersion.addVersion('0.11.25', '修改/rps/disposeCheck，最后一条校核通过时不会把前面不通过的单子也改为“通过”')
siteVersion.addVersion('0.11.26', '增加api: get_thisyear_data_avg')
siteVersion.addVersion('0.11.27', '修改/rps/getNoticeListOfUser，审校/校核通过或不通过也会通知')
siteVersion.addVersion('0.11.28', '新dompysite的图片目录不存在的问题修复')
siteVersion.addVersion('0.11.29', '修改/rps/getNoticeListOfUser，审校/校核通过或不通过会通知创建者')
siteVersion.addVersion('0.11.30', '升级接口rps/getRpsAuditRecord  ，original和target两个字段都是空对象时，返回的数据里没有此审核单')
siteVersion.addVersion('0.11.31', '增加按钮、文本、图元的hideScript支持')
siteVersion.addVersion('0.11.32', '升级接口rps/getRpsAuditRecord，运营提交的审核单，审核通过或不通过都不通知运营，只通知创建者')
siteVersion.addVersion('0.11.33', '修改：模板4db文件添加hideScript机制修改')
siteVersion.addVersion('0.11.34', '增加接口: /pointTable/exportPointTableV2')
siteVersion.addVersion('0.11.35', '接口修改: /pointTable/exportPointTableV2')
siteVersion.addVersion('0.11.36', '增加接口: project/getConfigMul')
siteVersion.addVersion('0.11.37', '增加接口: /getPysiteVersion')
siteVersion.addVersion('0.11.38', '增加接口: /strategy/getOneRoundLogOfVeryTime')
siteVersion.addVersion('0.11.39', '修改接口: /strategy/getOneRoundLogOfVeryTime，增加时间')
siteVersion.addVersion('0.11.40', '修改接口: /strategy/getOneRoundLogOfVeryTime，查询效率优化')
siteVersion.addVersion('0.11.41', '增加接口: /strategy/downloadOneDayLogOfVeryDate')
siteVersion.addVersion('0.11.42', '修改接口: /user/add 添加用户时的bug')
siteVersion.addVersion('0.11.43', '增加接口：/domUpdate/<processName>')
siteVersion.addVersion('0.11.44', '修改接口：/domUpdate/<processName> 增加domUpdate.exe启动后的运行情况检查')
siteVersion.addVersion('0.11.45', '修改接口：/version  增加接口：/dom/restart/<processName>')
siteVersion.addVersion('0.11.46', '创建历史表结构默认去掉update触发机制')
siteVersion.addVersion('0.11.47', '修改：/restart/<processName>')
siteVersion.addVersion('0.11.48', '新增：/processVersion   修改：/version')
siteVersion.addVersion('0.11.49', '修改：/processVersion 增加进程升级状态')
siteVersion.addVersion('0.11.50', '/processVersion redis中未记录进程升级状态的情形')
siteVersion.addVersion('0.11.51', '修改/operationRecord/downloadHistoryFile 返回问题bug')
siteVersion.addVersion('0.11.52', '新增接口：/rps')
siteVersion.addVersion('0.11.53', '新增接口：/equipment/getWarehouseIdOfRFIDReceiver')
siteVersion.addVersion('0.11.54', '增加工单评论流接口支持')
siteVersion.addVersion('0.11.55', '/rps/getNoticeListOfUser 容错处理')
siteVersion.addVersion('0.11.56', '/fdd/query 修改，增加评论流信息支持')
siteVersion.addVersion('0.11.57', '工单评论流接口修改')
siteVersion.addVersion('0.11.58', '修改/fdd/getWorkOrderFlow  增加用户中文名称')
siteVersion.addVersion('0.11.59', '修改： /operationRecord/downloadHistoryFile/<startTime>/<endTime>/<language>')
siteVersion.addVersion('0.11.60', '修改： /fdd/deleteCommentFromWorkOrder')
siteVersion.addVersion('0.11.61', '修改： 工单管理接口，将图片上传至OSS')
siteVersion.addVersion('0.11.62', '修改： /fdd/getWorkOrderFlow')
siteVersion.addVersion('0.11.63', '修改：send_alert_to_cloud_center')
siteVersion.addVersion('0.11.64', '修改：/project/saveConfig')
siteVersion.addVersion('0.11.65', '增加:/fdd/import')
siteVersion.addVersion('0.11.66', '增加:/project/deleteConfig')
siteVersion.addVersion('0.11.67', '增加log等级设置')
siteVersion.addVersion('0.11.68', '数据库连接中modbusclientcore的尽量分解')
siteVersion.addVersion('0.11.69', '增加：readOperationLogV2')
siteVersion.addVersion('0.11.70', '修改：readOperationLogV2，查询时改为用户名大小写不敏感')
siteVersion.addVersion('0.11.71', '修改：/warning/getRealtime 增加火灾模式字段')
siteVersion.addVersion('0.11.72', '/login修改为用户名精确匹配判断')
siteVersion.addVersion('0.11.73', '/fdd/getWorkOrderFlow 修改')
siteVersion.addVersion('0.11.74', '/pointData/setValue失败返回msg修改，/project/saveConfig编码问题处理')
siteVersion.addVersion('0.11.75', '升级：get_operation_log，支持超级用户cx返回所有日志')
siteVersion.addVersion('0.11.76', '修改: /get_operation_log')
siteVersion.addVersion('0.11.77', '修改/get_operation_log查询条件')
siteVersion.addVersion('0.11.78', '若userId在本地不存在则认为是访客权限')
siteVersion.addVersion('0.11.79', '/getTodayModeListOfTypes 修改')
siteVersion.addVersion('0.11.80', '注册key时更多日志增加')
siteVersion.addVersion('0.11.81', '增加：/weather/getForcastWeatherInfoV2/<strDate>/<nDays>')
siteVersion.addVersion('0.11.82', '增加：/webPublish 支持web發佈')
siteVersion.addVersion('0.11.83', '增加：/webPublish 支持web發佈 改進')
siteVersion.addVersion('0.11.84', '增加：/webPublish 支持web發佈 改進')
siteVersion.addVersion('0.11.85', '增加：/webPublish 支持web發佈 改進')
siteVersion.addVersion('0.11.86', '增加：/webPublish 支持web發佈 改進')
siteVersion.addVersion('0.11.87', '修改接口：/equipment/getInitAssetByIdentity')
siteVersion.addVersion('0.11.88', '语音播报增加per参数支持')
siteVersion.addVersion('0.11.89', '修改word报表生成机制')
siteVersion.addVersion('0.11.90', '/get_history_data_padded 支持s5历史数据查询')
siteVersion.addVersion('0.11.91', '/getOneRoundLogOfVeryTime 优化')
siteVersion.addVersion('0.11.92', '/增加：saveLogoImg')
siteVersion.addVersion('0.11.93', '/增加：/backendFile/add   /backendFile/get')
siteVersion.addVersion('0.11.94', '【domOMDebug】新增 数据采集 页面')
siteVersion.addVersion('0.11.95', '【domOMDebug】数据采集 修改样式')
siteVersion.addVersion('0.11.96', '增加接口：/backendFile/update')
siteVersion.addVersion('0.11.97', '【domOMDebug】数据采集 增加y轴自定义范围')
siteVersion.addVersion('0.11.98', '增加接口：/unit01/setValueMulti  /unit01/getValueMulti ')
siteVersion.addVersion('0.11.99', '【domOMDebug】数据采集 优化历史模式')
siteVersion.addVersion('0.12.0', 'importHistoryDataFile升级支持s5')
siteVersion.addVersion('0.12.1', '【domOMDebug】数据采集 实时模式初始化展示最近半小时数据，增加清空按钮')
siteVersion.addVersion('0.12.2', '增加myql底层配置的获取和修改接口')
siteVersion.addVersion('0.12.3', '增加BACNET_IFACE设置、获取接口')
siteVersion.addVersion('0.12.4', '修改/pointData/setValue ')
siteVersion.addVersion('0.12.5', '修改 /backendFile/add')
siteVersion.addVersion('0.12.6', '增加 /backendFile/download')
siteVersion.addVersion('0.12.7', '增加 策略dll文件下载统一接口：/logic/downloadSyslogicFiles')
siteVersion.addVersion('0.12.8', '数据采集页面y轴优化')
siteVersion.addVersion('0.12.9', '新增加接口：/point/insertModbusEquipmentPoints   /point/detectMissingModbusEquipmentPointsByLocalConfig')
siteVersion.addVersion('0.12.10', '新增点表管理接口')
siteVersion.addVersion('0.12.11', '修改/dom/restart/<process>')
siteVersion.addVersion('0.12.12', '修改/processVersion')
siteVersion.addVersion('0.12.13', '增加接口：/project/saveConfigByJsonFile')
siteVersion.addVersion('0.12.14', '新建点接口增加update至redis机制')
siteVersion.addVersion('0.12.15', 'processVersion支持domCloudMQTTCenter')
siteVersion.addVersion('0.12.16', '增加接口：支持本地项目名称修改')
siteVersion.addVersion('0.12.17', '/processVersion接口增加redis运行状态')
siteVersion.addVersion('0.12.18', '支持dcim接口')
siteVersion.addVersion('0.12.19', 'dcim接口修改')
siteVersion.addVersion('0.12.20', '/processVersion 将运行中的进程前置')
siteVersion.addVersion('0.12.21', '增加接口：/system/uploadModuleZip')
siteVersion.addVersion('0.12.22', '修改接口：/dcim/setRealtimeDataAndGetPointsToWrite')
siteVersion.addVersion('0.12.23', 'insert_history_data_mul日志强化')
siteVersion.addVersion('0.12.24', '增加cloudLogin接口用于云端转认证')
siteVersion.addVersion('0.12.25', '增加/network/get接口')
siteVersion.addVersion('0.12.26', '修改/point/updatePoint  /point/addOnePoint')
siteVersion.addVersion('0.12.27', '增加：/logic/getLogicList')
siteVersion.addVersion('0.12.28', '修改：/network/get')
siteVersion.addVersion('0.12.29', '修改：/warning/getRealtime')
siteVersion.addVersion('0.12.30', '兼容注册号在某些电脑上的意外')
siteVersion.addVersion('0.12.31', '增加：/logic/editConfig')
siteVersion.addVersion('0.12.32', '修改/network/get')
siteVersion.addVersion('0.12.33', '网络架构接口、实时报警接口支持能源管理')
siteVersion.addVersion('0.12.34', '修改/warning/getRealtime')
siteVersion.addVersion('0.12.35', '修改/network/get')
siteVersion.addVersion('0.12.36', '修改/network/get')
siteVersion.addVersion('0.12.37', '修改/warning/getRealtime')
siteVersion.addVersion('0.12.38', '新增策略增删改查接口')
siteVersion.addVersion('0.12.39', '新增策略启停接口')
siteVersion.addVersion('0.12.40', '修改:/logic/analyseMissingDependPoints 接口')
siteVersion.addVersion('0.12.41', '修改:/domUpdate/<processName>')
siteVersion.addVersion('0.12.42', '/network/get 兼容非自控系统服务器内网中的modbus设备')
siteVersion.addVersion('0.12.43', '修改/monitorResources')
siteVersion.addVersion('0.12.44', '增加/wizard/getStandardModbusConfig')
siteVersion.addVersion('0.12.45', '调试工具策略操作增加unit02表操作')
siteVersion.addVersion('0.12.46', '增加:/wizard/getAllStandardModbusEquipmentDefine')
siteVersion.addVersion('0.12.47', '增加:/wizard/saveModbusEquipmentOfBus')
siteVersion.addVersion('0.12.48', '/strategy/getOneRoundLogOfVeryTime 修改为查询目标时间附近5分钟内的日志')
siteVersion.addVersion('0.12.49', '增加: /wizard/testModbusConn')
siteVersion.addVersion('0.12.50', '修改: /wizard/testModbusConn')
siteVersion.addVersion('0.12.51', '增加/wizard/deleteBus')
siteVersion.addVersion('0.12.52', '增加/wizard/downloadStdModbusEquipManual')
siteVersion.addVersion('0.12.53', '修改：/wizard/testModbusConn')
siteVersion.addVersion('0.12.54', '仿真模式下可免授权')
siteVersion.addVersion('0.12.55', '增加domdb.4db上传、下载接口')
siteVersion.addVersion('0.12.56', '增加从云端下载domdb.4db接口')
siteVersion.addVersion('0.12.57', '/processVersion增加domUpdate')
siteVersion.addVersion('0.12.58', '/allusers接口支持用户的邮件和手机号信息读取')
siteVersion.addVersion('0.12.59', '修改：/logic/updateLogic')
siteVersion.addVersion('0.12.60', '当domdb误被无意设置为只读文件时，启动时修改为正常')
siteVersion.addVersion('0.12.61', '/getBACNET_IFACE修改：当BACNET_IFACE未配置时不在提示')
siteVersion.addVersion('0.12.62', 'standard_modbus_equipment_define改为从oss获取')
siteVersion.addVersion('0.12.63', '增加：/downloadManual/<key>')
siteVersion.addVersion('0.12.64', '增加：/deleteLogoImg/<strType>')
siteVersion.addVersion('0.12.65', '增加：/modscan/connect  /modscan/readOnce')
siteVersion.addVersion('0.12.66', '增加：/modscan/readOnce 增加双精度浮点')
siteVersion.addVersion('0.12.67', '修改: /logic/editName')
siteVersion.addVersion('0.12.68', '增加: /getUserOfRoleList')
siteVersion.addVersion('0.12.69', '增加: /getLogicList 增加策略云端版本')
siteVersion.addVersion('0.12.70', '修改：/getUserOfRoleList')
siteVersion.addVersion('0.12.71', '修改：/pointData/setValue返回结构修改为Json')
siteVersion.addVersion('0.12.72', '修改：后台进程管理接口bug修复')
siteVersion.addVersion('0.12.73', '增加/oss/uploadFile')
siteVersion.addVersion('0.12.74', '提示出计算机名')
siteVersion.addVersion('0.12.75', '增加进程回滚接口')
siteVersion.addVersion('0.13.1', '重大变化升级：开放永久授权')
siteVersion.addVersion('0.13.2', '修改/serviceData/getRealtime')
siteVersion.addVersion('0.13.3', '增加：/system/configFrpc')
siteVersion.addVersion('0.13.4', '修改/wizard/saveModbusEquipmentOfBus 重复性检查的bug')
siteVersion.addVersion('0.13.5', '调试工具中的默认通讯参数初始化，原来factory有的这里也加上了-golding')
siteVersion.addVersion('0.13.6', '调试工具中的默认通讯参数初始化，原来factory有的这里也加上了 V2-golding')
siteVersion.addVersion('0.13.7', '调试工具中的默认通讯参数初始化，原来factory有的这里也加上了 V3-golding')
siteVersion.addVersion('0.13.8', 'getMysqlConfig 兼容性处理')
siteVersion.addVersion('0.13.9', '调试工具向导中兼容同ip不同port的情形')
siteVersion.addVersion('0.13.10', '增加云端报表模板接口')
siteVersion.addVersion('0.13.11', '增加：/system/getDomFrpcCurrentConfig')
siteVersion.addVersion('0.13.12', '启停策略时增加线程名和策略名称的一致性检查处理')
siteVersion.addVersion('0.13.13', '增加进程暂缓运行处理接口')
siteVersion.addVersion('0.13.14', '修改/pauseProcess')
siteVersion.addVersion('0.13.15', '增加domBacnetCore配置文件设置和获取接口')
siteVersion.addVersion('0.13.16', '修改/getRealtimeWithPages')
siteVersion.addVersion('0.13.17', '增加：/point/matchStandardPoint')
siteVersion.addVersion('0.13.18', '增加：/search')
siteVersion.addVersion('0.13.19', '增加：domBackupMysql配置文件获取和设置接口')
siteVersion.addVersion('0.13.20', '修改domBackupMysql配置文件获取和设置接口')
siteVersion.addVersion('0.13.21', '增加：/point/getSourceType， 调试工具新建策略时选择策略列表改为从oss获取')
siteVersion.addVersion('0.13.22', '增加：/modscan/writeValue')
siteVersion.addVersion('0.13.23', 'get_history_data_padded接口增加对s5的预检，如果不存在5秒存储周期则返回1分钟数据')  #golding
siteVersion.addVersion('0.13.24', '增加：/network/queryHistoryOnlineStatus')
siteVersion.addVersion('0.13.25', '/warning/getRealtime bacnet网关、西门子plc在离线状态根据ping判断，log查询接口修改')
siteVersion.addVersion('0.13.26', '修改：/warning/getRealtime')
siteVersion.addVersion('0.13.27', '修改：/network/queryHistoryOnlineStatus')
siteVersion.addVersion('0.13.28', '修改：/warning/getRealtime  增加设备心跳包延迟秒数')
siteVersion.addVersion('0.13.29', '修改：/warning/getRealtime  增加Modbus设备的前后缀')
siteVersion.addVersion('0.13.30', '修改：点表管理中的单位字符集问题、上传zip包增加进程暂缓启动')
siteVersion.addVersion('0.13.31', '新增：/point/getStandardPointNameAndDesc')
siteVersion.addVersion('0.13.32', '处理经验增删后请求/get_plant无法获取到最新经验的问题')
siteVersion.addVersion('0.13.33', '启动domlogicParser.exe后等待结果json文件的等待时间放长')
siteVersion.addVersion('0.13.34', 'getRealtimeWithPages 关键字查询优化')
siteVersion.addVersion('0.13.35', '/operationRecord/addLogin 请求来源识别升级')
siteVersion.addVersion('0.13.36', '增加/system/getDisplayManage /system/setDisplayManage')
siteVersion.addVersion('0.13.37', '/pointTable/importPointTable 对导入的点表进行非法索引处理')
siteVersion.addVersion('0.13.38', '升级/point/matchStandardPoint   /point/getStandardPointNameAndDesc')
siteVersion.addVersion('0.13.39', '增加：/redis/updateMap')
siteVersion.addVersion('0.13.40', '处理策略配参参数为中文时的字符集问题')
siteVersion.addVersion('0.13.41', '增加组态模板文件管理接口')
siteVersion.addVersion('0.13.42', 'getConfig改为优先获取gbk')
siteVersion.addVersion('0.13.43', '增加：/wizard/getLocalTemplateFileList')
siteVersion.addVersion('0.13.44', '增加：/system/ProcessLogOnOffSet')
siteVersion.addVersion('0.13.45', '报表模板上传接口增加云端验证')
siteVersion.addVersion('0.13.46', '报表模板上传接口修改：只有当新增模板时才必须传入description')
siteVersion.addVersion('0.13.47', '增加记录addRecord的内容')
siteVersion.addVersion('0.13.48', '历史数据查询接口时间有误问题报错提示强化')
siteVersion.addVersion('0.13.49', '启动时CRITICAL记录')
siteVersion.addVersion('0.13.50', '/getLogicList增加策略摘要说明、/processVersion 增加domBacnetCore1-5')
siteVersion.addVersion('0.13.51', '增加进程日志开关状态获取接口')
siteVersion.addVersion('0.13.52', '增加：/system/turnOffAllLogs')
siteVersion.addVersion('0.13.53', '无窗口化处理')
siteVersion.addVersion('0.13.54', '从云端下载项目模板domdb.4db后执行点名前缀删除')
siteVersion.addVersion('0.13.55', '导入点表时点表预检错误输出修改')
siteVersion.addVersion('0.13.56', '/deleteTemplateFile 修改')
siteVersion.addVersion('0.13.57', '暂时屏蔽替换前缀')
siteVersion.addVersion('0.13.58', '修改：/downloadPeriodicUpdateManualByKey')
siteVersion.addVersion('0.13.59', '初始化domdb.4db时的机房前缀处理问题修复')
siteVersion.addVersion('0.13.60', '增加/wizard/syncTemplateFileToLocal')
siteVersion.addVersion('0.13.61', '/updatePoint source检查机制修改')
siteVersion.addVersion('0.13.62', '/importPointTable 增加点表补充机制')
siteVersion.addVersion('0.13.63', '增加：/logic/getEquipCommandLockProtect')
siteVersion.addVersion('0.13.64', '修改：/system/monitorResources')
siteVersion.addVersion('0.13.65', '/downloadManual 升级')
siteVersion.addVersion('0.13.66', '增加redis当前设置信息获取接口')
siteVersion.addVersion('0.13.67', '/getRealtimeWithPages优化')
siteVersion.addVersion('0.13.68', '查询点位操作记录接口升级')
siteVersion.addVersion('0.13.69', '查询点位操作记录接口升级')
siteVersion.addVersion('0.13.70', '新建或更新策略时发现dll版本高于OSS记录的策略版本则将OSS记录的策略版本跟更新一次')
siteVersion.addVersion('0.13.71', '修改：/getLogicList')
siteVersion.addVersion('0.13.72', '优化：/operation/logicRecordOutput, 增加:/strategy/removeTodayLogOfLogic')
siteVersion.addVersion('0.13.73', '修改：/operation/logicRecordOutput')
siteVersion.addVersion('0.13.74', '修改：/redis/getMemorySettings')
siteVersion.addVersion('0.13.75', '修改：/strategy/getOneRoundLogOfVeryTime')
siteVersion.addVersion('0.13.76', '修改：/pointData/setValue  增加操作记录')
siteVersion.addVersion('0.13.77', '修改: /operation/logicRecordOutput 增加按时间排序')
siteVersion.addVersion('0.13.78', '增加：/equipment/getAllEquipAssetInfo')
siteVersion.addVersion('0.13.79', '增加摘挂牌中点位写值安全性判断')
siteVersion.addVersion('0.13.80', '/getPlant接口修改，element查询时的残留event过滤处理')
siteVersion.addVersion('0.13.81', 'modbus标准设备类型中文名称不对应问题处理')
siteVersion.addVersion('0.13.82', '/pointData/setValue 增加传参区分是否插入操作记录')
siteVersion.addVersion('0.13.83', '增加/updateLogicOfLatestVersion')
siteVersion.addVersion('0.13.84', '修改：/updateLogicOfLatestVersion')
siteVersion.addVersion('0.13.85', '增加：/logic/getLogicVersion')
siteVersion.addVersion('0.13.86', '修改：/logic/updateLogicOfLatestVersion')
siteVersion.addVersion('0.13.87', '修改：优化/operation/logicRecordOutput排序耗时')
siteVersion.addVersion('0.13.88', '修改：优化/operation/logicRecordOutput 排序耗时')
siteVersion.addVersion('0.13.89', '/operation/logicRecordOutput 日志强化')
siteVersion.addVersion('0.13.90', '资产管理模板设备自检升级')
siteVersion.addVersion('0.13.91', '资产管理新增设备、修改设备时的参数校验修改')
siteVersion.addVersion('0.13.92', '资产管理新增设备、修改设备时的参数校验问题修改')
siteVersion.addVersion('0.13.93', '增加: /warning/deal')
siteVersion.addVersion('0.13.94', '报警接口增加忽略分钟数')
siteVersion.addVersion('0.13.95', '修改资产管理接口')
siteVersion.addVersion('0.13.96', '修改报警处理及获取接口')
siteVersion.addVersion('0.13.97', '修改：/warning/getRealtime')
siteVersion.addVersion('0.13.98', 'cx用户权限等级修改为10，增加 /system/getUpdateProgress')
siteVersion.addVersion('0.13.99', '修改：/system/getUpdateProgress')
siteVersion.addVersion('0.14.1', '修改：仪表接口配置中设备站号取整处理')
siteVersion.addVersion('0.14.2', '修改：/logic/getEquipCommandLockProtect 传入用户名判断摘挂牌下发权限')
siteVersion.addVersion('0.14.3', '修改：/operation/logicRecordOutput精确定位点名')
siteVersion.addVersion('0.14.4', '新增：/equipment/getEquipRatingParam')
siteVersion.addVersion('0.14.5', '修改：/equipment/getEquipRatingParam')
siteVersion.addVersion('0.14.6', '修改：修复确认故障时cx账户获取用户ID的问题')
siteVersion.addVersion('0.14.7', '修改：/warning/deal 关闭故障')
siteVersion.addVersion('0.14.8', '新增/system/diagnosis')
siteVersion.addVersion('0.14.9', 'warning/getRealtime增加暖通设备类型字段equipType')
siteVersion.addVersion('0.14.10', '增加：/wizard/downloadOMZip')
siteVersion.addVersion('0.14.11', '修复报警关闭时间缺失、增加点设置值失败信息内容')
siteVersion.addVersion('0.14.12', '修复报警关闭时间缺失、点设置值失败信息内容改进')
siteVersion.addVersion('0.14.13', '报警closeTime和状态修复')
siteVersion.addVersion('0.14.14', '点设置值失败信息内容改进')
siteVersion.addVersion('0.14.15', '升级/wizard/getLocalTemplateFileList 接口获取所有模板文件信息')
siteVersion.addVersion('0.14.16', 'cx用户ID修改为-1')
siteVersion.addVersion('0.14.17', 'warning/deal支持处理多条报警')
siteVersion.addVersion('0.14.18', '增加页面、组管理接口')
siteVersion.addVersion('0.14.19', 'web调试工具后台更新策略时const,point类型被冲掉的bug修复')
siteVersion.addVersion('0.14.20', '处理点表管理中单位含有上标情况的解码问题')
siteVersion.addVersion('0.14.21', '策略日志查询结果中替换策略自定义名称为空字符串')
siteVersion.addVersion('0.14.22', '增加接口：/point/addPoints')
siteVersion.addVersion('0.14.23', 'userofrole的cx账号属性需要为字符串')
siteVersion.addVersion('0.14.24', '增加dom/restartDomLogicAll接口')
siteVersion.addVersion('0.14.25', '增加：/page/updatePageContent')
siteVersion.addVersion('0.14.26', '根用户从allusers接口中额外移除')
siteVersion.addVersion('0.14.27', 'warning/add增加infoDetail支持')
siteVersion.addVersion('0.14.28', '组态编辑接口增加编辑权限管理')
siteVersion.addVersion('0.14.29', '组态编辑接口修改：text的id由前端算出')
siteVersion.addVersion('0.14.30', '/warning/add接口 bug修复')
siteVersion.addVersion('0.14.31', 'log_each_request修复尝试')
siteVersion.addVersion('0.14.32', '/warning/add接口 继续改进兼容')
siteVersion.addVersion('0.14.33', '组态界面修改接口字体颜色传参修改')
siteVersion.addVersion('0.14.34', '组态编辑权限锁加入userId')
siteVersion.addVersion('0.14.35', '/updatePageContent 背景框样式修改为整数字符串')
siteVersion.addVersion('0.14.36', '/updatePageContent 背景框样式修改为整数字符串')
siteVersion.addVersion('0.14.37', 'modbus_point_table.xlsx更新后自动解压至domModbusServer路径下')
siteVersion.addVersion('0.14.38', 'AI决策训练集测试集的比例选择，增加AI_rule_update_time、script_rule_update_time redis键')
siteVersion.addVersion('0.14.39', '增加AI_rule_update_info、script_rule_update_info redis键')
siteVersion.addVersion('0.14.40', 'AI及rule定义增加每个规则的updatetime')
siteVersion.addVersion('0.14.41', '/updatePageContent颜色转换修改')
siteVersion.addVersion('0.14.42', '/script_rule_update_time redis键值')
siteVersion.addVersion('0.14.43', '增加：/logic/upgradeSeparateThreads')
siteVersion.addVersion('0.14.44', '/updatePageContent增加高级自定义组件')
siteVersion.addVersion('0.14.45', '组态操作修改为页面锁')
siteVersion.addVersion('0.14.46', 'StandardModbusEquipmentDefine.json缓存进redis')
siteVersion.addVersion('0.14.47', '/get_plant兼容自定义组件中的json错配情况')
siteVersion.addVersion('0.14.48', '策略单线程化处理升级（兼容分线程）')
siteVersion.addVersion('0.14.49', '增加：/page/searchTemplateByPointKeyword')
siteVersion.addVersion('0.14.50', 'DebugTool组态获取接口与om分离')
siteVersion.addVersion('0.14.51', 'modscan读取十六进制和二进制问题处理')
siteVersion.addVersion('0.14.52', '增加接口：获取一个模板内的所有标准设备列表')
siteVersion.addVersion('0.14.53', '组态编辑页面锁增加mac地址')
siteVersion.addVersion('0.14.54', '升级页面、页面组编辑接口')
siteVersion.addVersion('0.14.55', '/equipment/getRoomEquipmentListAndStatus 增加RoomName')
siteVersion.addVersion('0.14.56', '增加logicPush接口')
siteVersion.addVersion('0.14.57', '/updatePageContent 增加button')
siteVersion.addVersion('0.14.58', '增加：/logicPush/getLogicDetails')
siteVersion.addVersion('0.14.59', '/updatePageContent 新增checkbox')
siteVersion.addVersion('0.14.60', '/updatePageContent checkbox类型输入兼容字符串')
siteVersion.addVersion('0.14.61', '/updatePageContent checkbox idGroup和fontSize兼容字符串')
siteVersion.addVersion('0.14.62', '/updatePageContent 增加图片支持')
siteVersion.addVersion('0.14.63', '导入点表接口移除按索引降序排列部分')
siteVersion.addVersion('0.14.64', '报表生成接口调用时转发至domJobs')
siteVersion.addVersion('0.14.65', '/updatePageContent 修改')
siteVersion.addVersion('0.14.66', '修改：/backendFile/update')
siteVersion.addVersion('0.14.67', 'list_button增加sourceType字段')
siteVersion.addVersion('0.14.68', '/backendFile/update 修改')
siteVersion.addVersion('0.14.69', '/updatePageContent 修改button图片处理方式')
siteVersion.addVersion('0.14.70', '增加图库管理接口')
siteVersion.addVersion('0.14.71', '增加图片、动画删除接口')
siteVersion.addVersion('0.14.72', '策略日志接口升级')
siteVersion.addVersion('0.14.73', '组态管理中颜色rgb转换升级')
siteVersion.addVersion('0.14.74', '/wizard/saveModbusEquipmentOfBus 子站后缀做留空兼容')
siteVersion.addVersion('0.14.75', 'warning/getRealtime服务器网卡在离线逻辑修改')
siteVersion.addVersion('0.14.76', '增加页面、分组顺序修改接口')
siteVersion.addVersion('0.14.77', 'button设置值兼容点名')
siteVersion.addVersion('0.14.78', '增加接口：/strategy/getLatestRoundLogOfTestFailure')
siteVersion.addVersion('0.14.79', '修改：/wizard/downloadStdModbusEquipManual  初始化项目工程文件时替换水流动画中的机房前缀')
siteVersion.addVersion('0.14.80', '策略日志接口提供旧版格式返回和新版格式返回并存')
siteVersion.addVersion('0.14.81', '/updatePageContent 新增管道')
siteVersion.addVersion('0.14.82', '修改/addElementToLibImage')
siteVersion.addVersion('0.14.83', "/configRemoteAccess修改")
siteVersion.addVersion('0.14.84', "/updatePageContent 增加标准设备")
siteVersion.addVersion('0.14.85', "修改: /getPageInfo")
siteVersion.addVersion('0.14.86', "/page/getStandardEquipmentOfTemplateFile 增加入口图元图片id")
siteVersion.addVersion('0.14.87', "pointData/setValue 增加写入失败后的重写入")
siteVersion.addVersion('0.14.88', "页面分组修改合并进入/updagePageInfo")
siteVersion.addVersion('0.14.89', "增加：/listLocalTemplateFileNames")
siteVersion.addVersion('0.14.90', "修改:/fdd/query")
siteVersion.addVersion('0.14.91', "增加：/logic/listLogicByType")
siteVersion.addVersion('0.14.92', "增加：/fdd/getUpdate")
siteVersion.addVersion('0.14.93', "修改：/fdd/getUpdate")
siteVersion.addVersion('0.14.94', "修改：/fdd/getUpdate")
siteVersion.addVersion('0.14.95', "修改：/fdd/addMaintainanceFault")
siteVersion.addVersion('0.14.96', "修改：/fdd/addCommentToWorkOrder")
siteVersion.addVersion('0.14.97', "修改：/fdd/getUpdate")
siteVersion.addVersion('0.14.98', "修改：/system/configRemoteAccess")
siteVersion.addVersion('0.14.99', "新增：/fdd/addVisit  /fdd/getWorkOrderUpdate")
siteVersion.addVersion('0.15.0', "增加图库管理（DOMImageLib.4db)")
siteVersion.addVersion('0.15.1', "图库管理接口修改")
siteVersion.addVersion('0.15.2', "新增：/page/getStandardEquipmentOfAllTemplateFiles")
siteVersion.addVersion('0.15.3', "/getWorkOrderUpdate 修改未：工单的修改、创建、评论执行动作当前用户不可见")
siteVersion.addVersion('0.15.4', "修改图库管理接口")
siteVersion.addVersion('0.15.5', "/updatePageContent 支持矩形框")
siteVersion.addVersion('0.15.6', "/updatePageContent 修改")
siteVersion.addVersion('0.15.7', "修改：/get_plant_DebugTool 矩形框增加透明度")
siteVersion.addVersion('0.15.8', "启动时将所有页面的内容刷新进redis")
siteVersion.addVersion('0.15.9', "get_plant_DebugTool标准设备增加templateName和entranceGroupId")
siteVersion.addVersion('0.15.10', "修改：/updatePageContent")
siteVersion.addVersion('0.15.11', "启动时记录一次启动时间")
siteVersion.addVersion('0.15.12', "查询策略日志时文件过大则返回提示")
siteVersion.addVersion('0.15.13', "/updatePageContent修改自定义组件时内容增加gbk编码")
siteVersion.addVersion('0.15.14', "启动时若domdb中的表格时间大于domModbusServer下的excel点表时间则release一次modbus_point_table.xlsx")
siteVersion.addVersion('0.15.15', "增加：/requestAndSaveCalendarData")
siteVersion.addVersion('0.15.16', "组态：图片和标准设备增加用户自定义名称")
siteVersion.addVersion('0.15.17', "修改/getPlant")
siteVersion.addVersion('0.15.18', "图片的bindType的获取兼容非0也非1的情况")
siteVersion.addVersion('0.15.19', "增加历史报警、历史后台报表导出接口")
siteVersion.addVersion('0.15.20', "修改新增页面时分组号乱序问题")
siteVersion.addVersion('0.15.21', "新增domdb.4db备份下载接口、初始化工单设置接口")
siteVersion.addVersion('0.15.22', "工单查询返回所有变化的工单（包括被评论过的）；修改/getPngImageList；/pointData/getRealtimeWithPages关键词查询不再按顺序查询；组态编辑不再存入debugtool专用缓存")
siteVersion.addVersion('0.15.23', "修改：log_critical_event")
siteVersion.addVersion('0.15.24', "增加网络命令ping接口调用支持")
siteVersion.addVersion('0.15.25', "增加网络命令ping接口调用支持，改进")
siteVersion.addVersion('0.15.26', "增加网络命令ping接口调用支持，改进2")
siteVersion.addVersion('0.15.27', "增加网络命令ping接口调用支持，改进3")
siteVersion.addVersion('0.15.28', "增加:/fdd/getWorkOrderMembers")
siteVersion.addVersion('0.15.29', "增加：/killOM")
siteVersion.addVersion('0.15.30', "修改：/fdd/getGroupMembersOfAdmin")
siteVersion.addVersion('0.15.31', "修改：/updatePageContent")
siteVersion.addVersion('0.15.32', "修改：/updatePageContent添加动画后将动画的图片复制进入静态路径下")
siteVersion.addVersion('0.15.33', "修改：/pointTable/exportPointTableV2增加排序，删除页面后元素乱入问题处理")
siteVersion.addVersion('0.15.34', "修改：/fdd/query")
siteVersion.addVersion('0.15.35', "修改：/fdd/query")
siteVersion.addVersion('0.15.36', "若StandardModbusEquipmentDefine.json下载失败返回提示信息")
siteVersion.addVersion('0.15.37', "修改工单查询机制")
siteVersion.addVersion('0.15.38', "warning/getRealtime中网络架构设备离线信息从redis获取")
siteVersion.addVersion('0.15.39', "工单操作修改")
siteVersion.addVersion('0.15.40', "修改工单操作及查询接口")
siteVersion.addVersion('0.15.41', "修改: /getGroupMembersOfAdmin  /processFault")
siteVersion.addVersion('0.15.42', "修改: /saveImgToOSS")
siteVersion.addVersion('0.15.43', "增加：/setSiteSimulationMode")
siteVersion.addVersion('0.15.44', "修改：/pointData/setValue")
siteVersion.addVersion('0.15.45', "处理所有RedisManager.get('all_point_info')读取失败的情况")

