import unittest
from siteunittest.testAll import TestList
from HTMLTestRunner import HTMLTestRunner
# 测试指定模块，并生成html报表
if __name__ == '__main__':
    suite = unittest.TestSuite()

    tests = [TestList("test_third_party_upload"), TestList("test_divide")]
    suite.addTests(tests)

    # with open('UnittestTextReport.txt', 'a') as  f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #     runner.run(suite)



    # runner = unittest.TextTestRunner(verbosity=2)
    # runner.run(suite)

    with open('HTMLReport.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)


